#! /usr/bin/python
import sys
import pygame as P
import math as M
import time as T
import random as R
import mandelutil as U
import mandelinit
import mandelgrid 
import mandelcount
import mandelcolors
PI=M.pi
P.init()

black=[0,0,0]
red=[255,0,0]
green=[0,128,0]
blue=[0,0,128]
white=[255,255,255]


def usage():
    print " Usage:", "pyfractal"," width height cx cy radius r_freq g_freq blue_freq max_iterations "
    return


def main(  ):
    if len(sys.argv) != 10 :
        usage()
        exit(0)
    else:
        size = width , height = int(sys.argv[1]), int(sys.argv[2])
        center= cx,cy = float(sys.argv[3]),float(sys.argv[4])
        radius= float(sys.argv[5])
        freq=[r_freq,g_freq,blue_freq]=float(sys.argv[6]),float(sys.argv[7]),float(sys.argv[8])
        Max_iter=int(sys.argv[9])
        S = mandelinit.init(size,white)
        for j in (range(size[1])[::-1]):
            for i in range(size[0]):
                z=mandelgrid.gridtocomplex(center,radius,size,(i,j))
                z=complex(z[0],z[1])
                count=mandelcount.z_count(z,2,Max_iter)
                kkolor=mandelcolors.Make_color(Max_iter,freq,count)
                S.set_at((i,j),kkolor)
            if j % 12 == 0: U.redraw()
        U.loop()

if __name__=="__main__":
    main()
#vi:syntax=python    
